#!/usr/bin/env bash

count_raw() {
   # $1 string.
   st=$(echo $1 | sed 's/\\033\[[0-9;]*m//g')
   echo ${#st}
}

# Colors.
NC='\033[0m'
RED='\033[1;31m'
GRN='\033[1;32m'
BLU='\033[1;34m'
YLW='\033[1;33m'
PRP='\033[1;35m'
GRY='\033[1;37m'

# Line 1.
GL1="${GRY}0${RED}==${YLW}[${GRY}=====>${NC} Welcome to ${GRN}$(uname -n)${NC}, ${YLW}$(whoami)${NC}! ${GRY}<=====${YLW}]${RED}==${GRY}0${NC}"

# Line 2.
GL2=`date "+${BLU}%A ${GRY}%d/%m/%Y ${PRP}%H:%M${NC}"`

# Calculate line 2 centering.
l1=$(count_raw "$GL1")
l2=$(count_raw "$GL2")
# Get the amount of spaces to insert into the left.
side=$(((l1-l2)/2))
SPACES=""
for i in $(seq 1 $side); do
   SPACES="${SPACES} "
done
# If length-parity between both lines is a mismatch, add a single character.
[ "$(((l1 + l2) % 2))" = "1" ] && APPEND="." || APPEND=""
L2="${SPACES}$GL2${APPEND}"

echo -e "$GL1"
echo -e "$L2"
echo ""
